### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Elinow** [PacktPublishing/Java-9-Concurrency-Cookbook-Second-Edition#1]
Looks like a typo in com.packtpub.java9.concurrency.cookbook.chapter01.recipe04.main.Main
	// Waits five seconds
	TimeUnit.SECONDS.sleep(5000);
Correct:
	// Waits for five seconds
	TimeUnit.SECONDS.sleep(5);

**Comment by sonam-packt** [comment]
Please reopen if the issue still persist.
